version: '3.8'

services:

  fileserver:
    deploy:
      replicas: 10

  frontend_en:
    deploy:
      replicas: 5

  frontend_ru:
    deploy:
      replicas: 5

  app_ru:
    deploy:
      replicas: 5

  app_en:
    deploy:
      replicas: 5

  downloader:
    deploy:
      replicas: 3

  api:
    deploy:
      replicas: 5
