version: '3.8'

x-logging:
  &default-logging
  options:
    max-size: "512m"

services:

  nginx:
    deploy:
      replicas: 40
    logging: *default-logging

  mongo:
    deploy:
      mode: global
    image: pastvu/mongo:3.2.22
    networks:
      - mongo
    volumes:
      - mongo:/data/db
    logging: *default-logging

  app_ru:
    deploy:
      replicas: 10
    secrets:
      - pastvu_smtp_host
      - pastvu_smtp_user
      - pastvu_smtp_pass
      - pastvu_log_pass
      - pastvu_yandex_api_key
      - pastvu_google_api_key
    logging: *default-logging

  app_en:
    deploy:
      replicas: 10
    secrets:
      - pastvu_smtp_host
      - pastvu_smtp_user
      - pastvu_smtp_pass
      - pastvu_log_pass
      - pastvu_yandex_api_key
      - pastvu_google_api_key
    logging: *default-logging

  api:
    deploy:
      replicas: 5
    image: pastvu/pastvu:${TAG:?ERR}
    networks:
      - backend
    configs:
      - config.js
    logging: *default-logging

  uploader:
    deploy:
      mode: global
    logging: *default-logging

  downloader:
    deploy:
      replicas: 3
    logging: *default-logging

  notifier_ru:
    deploy:
      mode: global
      placement:
        constraints:
          - node.labels.pastvu.pastvu-data == true
    networks:
      - backend
    image: pastvu/pastvu:${TAG:?ERR}
    environment:
      - NOTIFIER=true
      - DOMAIN
      - PROTOCOL
    configs:
      - config.js
    secrets:
      - pastvu_smtp_host
      - pastvu_smtp_user
      - pastvu_smtp_pass
      - pastvu_log_pass
    logging: *default-logging
 
  notifier_en:
    deploy:
      mode: global
      placement:
        constraints:
          - node.labels.pastvu.pastvu-data == true
    networks:
      - backend
    image: pastvu/pastvu:${TAG_EN:?ERR}
    environment:
      - LANG=en
      - NOTIFIER=true
      - DOMAIN
      - PROTOCOL
    configs:
      - config.js
    secrets:
      - pastvu_smtp_host
      - pastvu_smtp_user
      - pastvu_smtp_pass
      - pastvu_log_pass
    logging: *default-logging

networks:
  mongo:
    driver: overlay
    attachable: true
  backend:

secrets:
  pastvu_smtp_host:
    external: true
  pastvu_smtp_user:
    external: true
  pastvu_smtp_pass:
    external: true
  pastvu_log_pass:
    external: true
  pastvu_yandex_api_key:
    external: true
  pastvu_google_api_key:
    external: true

configs:
  config.js:
    file: ${CONFIG:?ERR}
    name: pastvu_config_${CONFIG_TAG:?ERR}

volumes:
  mongo:
