version: '3.8'

x-logging:
  &default-logging
  options:
    max-size: "512m"

services:

  api:
    deploy:
      replicas: 5
    image: pastvu/pastvu:${TAG:?ERR}
    networks:
      - backend
    configs:
      - config.js
    logging: *default-logging

  nginx:
    deploy:
      labels:
        swarmpit.service.deployment.autoredeploy: 'true'
      replicas: 2
    logging: *default-logging

  mongo:
    image: ${MONGO_IMAGE}
    volumes:
      - mongo:/data/db
    logging: *default-logging

  app_ru:
    deploy:
      replicas: 4
      labels:
        swarmpit.service.deployment.autoredeploy: 'true'
      update_config:
        order: start-first
    secrets:
      - pastvu_log_pass
    networks:
      - mailcatcher
    logging: *default-logging

  app_en:
    deploy:
      replicas: 4
      labels:
        swarmpit.service.deployment.autoredeploy: 'true'
      update_config:
        order: start-first
    secrets:
      - pastvu_log_pass
    networks:
      - mailcatcher
    logging: *default-logging
    
  uploader:
    deploy:
      labels:
        swarmpit.service.deployment.autoredeploy: 'true'
    logging: *default-logging
        
  downloader:
    deploy:
      labels:
        swarmpit.service.deployment.autoredeploy: 'true'
    logging: *default-logging

  sitemap:
    deploy:
      labels:
        swarmpit.service.deployment.autoredeploy: 'true'
    logging: *default-logging

  notifier_ru:
    deploy:
      mode: global
      placement:
        constraints:
          - node.labels.pastvu.pastvu-data == true
    networks:
      - backend
    image: pastvu/pastvu:${TAG:?ERR}
    environment:
      - NOTIFIER=true
      - DOMAIN
      - PROTOCOL
    configs:
      - config.js
    secrets:
      - pastvu_log_pass
    logging: *default-logging
 
  notifier_en:
    deploy:
      mode: global
      placement:
        constraints:
          - node.labels.pastvu.pastvu-data == true
    networks:
      - backend
    image: pastvu/pastvu:${TAG_EN:?ERR}
    environment:
      - LANG=en
      - NOTIFIER=true
      - DOMAIN
      - PROTOCOL
    configs:
      - config.js
    secrets:
      - pastvu_log_pass
    logging: *default-logging

networks:
  backend:
    driver: overlay
    attachable: true
  mailcatcher:


secrets:
  pastvu_log_pass:
    external: true

configs:
  config.js:
    file: ${CONFIG}
    name: pastvu_config_${CONFIG_TAG}

volumes:
  mongo:
    name: ${MONGO_VOLUME}
