version: '3.8'
services:
  nginx:
    networks:
      - traefik-public
    deploy:
      placement:
        constraints:
          - node.labels.pastvu.pastvu-data == true
      labels:
        # ENABLE TRAEFIK
        - traefik.enable=true
        - traefik.docker.network=traefik-public
        - traefik.constraint-label=traefik-public

        # MIDDLEWARE DEFINITIONS
        # REDIRECT WWW TO NON-WWW
        - traefik.http.middlewares.www-redirect.redirectregex.regex=^https?://w+\.${DOMAIN}/(.*)
        - traefik.http.middlewares.www-redirect.redirectregex.replacement=https://${DOMAIN}/$${1}
        - traefik.http.middlewares.www-redirect.redirectregex.permanent=true

        # HTTP
        - traefik.http.routers.pastvu-http.rule=HostRegexp(`${DOMAIN}`,`{sub:w+}.${DOMAIN}`)
        - traefik.http.routers.pastvu-http.entrypoints=http
        - traefik.http.routers.pastvu-http.middlewares=www-redirect,https-redirect

        # HTTPS
        - traefik.http.routers.pastvu-nginx.rule=Host(`${DOMAIN}`)&&PathPrefix(`/download`, `/sitemap`, `/files`, `/_`)
        - traefik.http.routers.pastvu-nginx.entrypoints=https
        - traefik.http.routers.pastvu-nginx.tls=true
        - traefik.http.routers.pastvu-nginx.tls.certresolver=le
        - traefik.http.routers.pastvu-nginx.priority=2000

        # ENABLE LOADBALANCER
        - traefik.http.services.pastvu-nginx.loadbalancer.server.port=80

# FRONTEND =============================================================================

  frontend_ru:
    image: pastvu/frontend:${TAG}
    networks:
      - traefik-public
    deploy:
      labels:
        # ENABLE TRAEFIK
        - traefik.enable=true
        - traefik.docker.network=traefik-public
        - traefik.constraint-label=traefik-public

        # DEFAULT
        - traefik.http.routers.pastvu-frontend-ru-default.rule=Host(`${DOMAIN}`)&&PathPrefix(`/js`, `/img`, `/style`, `/tpl`)
        - traefik.http.routers.pastvu-frontend-ru-default.entrypoints=https
        - traefik.http.routers.pastvu-frontend-ru-default.tls=true
        - traefik.http.routers.pastvu-frontend-ru-default.tls.certresolver=le
        - traefik.http.routers.pastvu-frontend-ru-default.priority=100

        # COOKIE RU
        - traefik.http.routers.pastvu-frontend-ru-cookie.rule=Host(`${DOMAIN}`)&&PathPrefix(`/js`, `/img`, `/style`, `/tpl`)&&HeadersRegexp(`Cookie`, `past.lang=ru`)
        - traefik.http.routers.pastvu-frontend-ru-cookie.entrypoints=https
        - traefik.http.routers.pastvu-frontend-ru-cookie.tls=true
        - traefik.http.routers.pastvu-frontend-ru-cookie.tls.certresolver=le
        - traefik.http.routers.pastvu-frontend-ru-cookie.priority=400

        # ENABLE LOADBALANCER
        - traefik.http.services.pastvu-frontend-ru.loadbalancer.server.port=80

  frontend_en:
    image: pastvu/frontend:${TAG_EN}
    networks:
      - traefik-public
    deploy:
      labels:
        # ENABLE TRAEFIK
        - traefik.enable=true
        - traefik.docker.network=traefik-public
        - traefik.constraint-label=traefik-public

        # ACCEPT-LANG
        - traefik.http.routers.pastvu-frontend-en-acclang.rule=Host(`${DOMAIN}`)&&PathPrefix(`/js`, `/img`, `/style`, `/tpl`)&&HeadersRegexp(`Accept-Language`, `^en.*`)
        - traefik.http.routers.pastvu-frontend-en-acclang.entrypoints=https
        - traefik.http.routers.pastvu-frontend-en-acclang.tls=true
        - traefik.http.routers.pastvu-frontend-en-acclang.tls.certresolver=le
        - traefik.http.routers.pastvu-frontend-en-acclang.priority=200

        # COOKIE EN
        - traefik.http.routers.pastvu-frontend-en-cookie.rule=Host(`${DOMAIN}`)&&PathPrefix(`/js`, `/img`, `/style`, `/tpl`)&&HeadersRegexp(`Cookie`, `past.lang=en`)
        - traefik.http.routers.pastvu-frontend-en-cookie.entrypoints=https
        - traefik.http.routers.pastvu-frontend-en-cookie.tls=true
        - traefik.http.routers.pastvu-frontend-en-cookie.tls.certresolver=le
        - traefik.http.routers.pastvu-frontend-en-cookie.priority=300

        # ENABLE LOADBALANCER
        - traefik.http.services.pastvu-frontend-en.loadbalancer.server.port=80

# API =============================================================================
#
  api:
    networks:
      - traefik-public
    deploy:
      placement:
        constraints:
          - node.labels.pastvu.pastvu-data == true
      labels:
        # ENABLE TRAEFIK
        - traefik.enable=true
        - traefik.docker.network=traefik-public
        - traefik.constraint-label=traefik-public

        # CORS MIDDLEWARE
        - traefik.http.middlewares.cors-headers.headers.accesscontrolalloworiginlist=*

        # API
        - traefik.http.routers.pastvu-api.rule=Host(`${DOMAIN}`)&&PathPrefix(`/api2`)
        - traefik.http.routers.pastvu-api.entrypoints=https
        - traefik.http.routers.pastvu-api.tls=true
        - traefik.http.routers.pastvu-api.tls.certresolver=le
        - traefik.http.routers.pastvu-api.middlewares=cors-headers
        - traefik.http.routers.pastvu-api.priority=3000

        # LOADBALANCER
        - traefik.http.services.pastvu-api.loadbalancer.server.port=3000

  app_ru:
    networks:
      - traefik-public
    deploy:
      placement:
        constraints:
          - node.labels.pastvu.pastvu-data == true
      labels:
        # ENABLE TRAEFIK
        - traefik.enable=true
        - traefik.docker.network=traefik-public
        - traefik.constraint-label=traefik-public

        # DEFAULT
        - traefik.http.routers.pastvu-ru-default.rule=Host(`${DOMAIN}`)
        - traefik.http.routers.pastvu-ru-default.entrypoints=https
        - traefik.http.routers.pastvu-ru-default.tls=true
        - traefik.http.routers.pastvu-ru-default.tls.certresolver=le
        - traefik.http.routers.pastvu-ru-default.priority=10

        # COOKIE RU
        - traefik.http.routers.pastvu-ru-cookie.rule=Host(`${DOMAIN}`)&&HeadersRegexp(`Cookie`, `past.lang=ru`)
        - traefik.http.routers.pastvu-ru-cookie.entrypoints=https
        - traefik.http.routers.pastvu-ru-cookie.tls=true
        - traefik.http.routers.pastvu-ru-cookie.tls.certresolver=le
        - traefik.http.routers.pastvu-ru-cookie.priority=30

        # LOADBALANCER
        - traefik.http.services.pastvu-ru.loadbalancer.server.port=3000
        - traefik.http.services.pastvu-ru.loadbalancer.sticky.cookie=true
        - traefik.http.services.pastvu-ru.loadbalancer.sticky.cookie.name=app_ru

  app_en:
    networks:
      - traefik-public
    deploy:
      placement:
        constraints:
          - node.labels.pastvu.pastvu-data == true
      labels:
        # ENABLE TRAEFIK
        - traefik.enable=true
        - traefik.docker.network=traefik-public
        - traefik.constraint-label=traefik-public

        # ACCEPT LANG
        - traefik.http.routers.pastvu-en-acclang.rule=Host(`${DOMAIN}`)&&HeadersRegexp(`Accept-Language`, `^en.*`)
        - traefik.http.routers.pastvu-en-acclang.entrypoints=https
        - traefik.http.routers.pastvu-en-acclang.tls=true
        - traefik.http.routers.pastvu-en-acclang.tls.certresolver=le
        - traefik.http.routers.pastvu-en-acclang.priority=20

        # COOKIE EN
        - traefik.http.routers.pastvu-en-cookie.rule=Host(`${DOMAIN}`)&&HeadersRegexp(`Cookie`, `past.lang=en`)
        - traefik.http.routers.pastvu-en-cookie.entrypoints=https
        - traefik.http.routers.pastvu-en-cookie.tls=true
        - traefik.http.routers.pastvu-en-cookie.tls.certresolver=le
        - traefik.http.routers.pastvu-en-cookie.priority=40

        # LOADBALANCER
        - traefik.http.services.pastvu-en.loadbalancer.server.port=3000
        - traefik.http.services.pastvu-en.loadbalancer.sticky.cookie=true
        - traefik.http.services.pastvu-en.loadbalancer.sticky.cookie.name=app_en

  uploader:
    networks:
      - traefik-public
    deploy:
      placement:
        constraints:
          - node.labels.pastvu.pastvu-data == true
      labels:
        # ENABLE TRAEFIK
        - traefik.enable=true
        - traefik.docker.network=traefik-public
        - traefik.constraint-label=traefik-public

        # HTTPS
        - traefik.http.routers.pastvu-uploader.rule=Host(`${DOMAIN}`)&&PathPrefix(`/upload`)
        - traefik.http.routers.pastvu-uploader.entrypoints=https
        - traefik.http.routers.pastvu-uploader.tls=true
        - traefik.http.routers.pastvu-uploader.tls.certresolver=le
        - traefik.http.routers.pastvu-uploader.priority=1000

        # ENABLE LOADBALANCER
        - traefik.http.services.pastvu-uploader.loadbalancer.server.port=3001

  downloader:
    networks:
      - traefik-public
    deploy:
      placement:
        constraints:
          - node.labels.pastvu.pastvu-data == true

networks:
  traefik-public:
    external: true
